
[build]
  # This will be your default build command
  command = "./build.sh"
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "public"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.51"

[context.production.environment]
  HUGO_VERSION = "0.51"

[context.staging]
  # This will be your default build command
  command = "./build.sh"
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "public"
  [context.staging.environment]
    HUGO_VERSION = "0.51"
